apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=saadpatel2400/devops-app
    argocd-image-updater.argoproj.io/myapp.update-strategy: newest-build
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^dev-[a-f0-9]+$
    argocd-image-updater.argoproj.io/myapp.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myapp.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:AutoScaleOps/values-dev.yaml

spec:
  project: default
  source:
    repoURL: https://github.com/psaad2400/gitops-k8s-devops-platform
    targetRevision: main
    path: AutoScaleOps
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true