apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "autoscaleops.fullname" . }}
  namespace: monitoring
  labels:
    release: monitoring              # must match helm release name
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: autoscaleops                 # your service label
  endpoints:
    - port: http                     # port name in your service
      path: /metrics
      interval: 15s