apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app
  namespace: monitoring
  labels:
    release: monitoring              # must match helm release name
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: devops-app-autoscaleops   # your service label
  endpoints:
    - port: http                     # port name in your service
      path: /metrics
      interval: 15s